### ISSUE TITLE
Dynamo Crashing after lunching window the second time

### ISSUE THREAD

**Issue by BadAstronaut** [ksobon/Mandrill#65]
What did you do?
The first time i run the graph and lunch the window it works perfectly but if i close the window and hit lunch again or close dynamo and re run i get the error

What did you expect to see?
the window with the graph

What did you see instead?
error

What packages or external references (if any) were used?
Mandrill 2020.2.1

Stack Trace
The process cannot access the file 'C:\Users\Acbim\AppData\Roaming\Dynamo\Dynamo Revit\2.3\packages\Archi-lab_Mandrill\bin\eowp.exe' because it is being used by another process.

at EO.Internal.ji.a(String A_0, Byte[] A_1)
at Mandrill.ChromeWindow.MandrillWindow..ctor()
at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
at System.Windows.Controls.Primitives.ButtonBase.OnClick()
at System.Windows.Controls.Button.OnClick()
at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ksobon** [comment]
@BadAstronaut what version of Revit/Dynamo/DynamoRevit are you using? I want to make sure that I can re-create the issue.

**Comment by BadAstronaut** [comment]
Thanks a lot Konrad. here is the file im using and info you requested
https://www.notion.so/rzlazo/Dynamo-13c46d858b874800bac1c8c5f112eabc

**Comment by ksobon** [comment]
@BadAstronaut so the issue that you have been seeing is hopefully solved now. I did a general update to Mandrill to bring it up to latest version of EO WebBrowser, and that should have resolved the need for eowp.exe to be launched directly from Mandrill. The library managed that itself now. Anyways, I won't bother you with the details. The long story short is that it should be fixed. Please update your Mandrill package to: 2021.1.1 and that should be resolved.

**Comment by BadAstronaut** [comment]
My god! your the best man! worked like a charm!! thanks a lot for the help!

**Comment by ksobon** [comment]
@BadAstronaut please consider supporting archi-lab.net via Patreon: https://www.patreon.com/archilab Funding that I receive on Patreon helps me keep these plugins updated, and working. In case of Mandrill it also pays for the license of EO Web Browser that the plugin uses. 

Cheers!

**Comment by BadAstronaut** [comment]
Done! i participate in the initial funding for mandrill i just sign in for the patreon. thanks for doing what you do!

**Comment by ksobon** [comment]
Oh! Thank you. That's great. That initial GoFund Me paid for the initial license cost, and yearly renewals for the next year after that. Since then, I have been paying the renewal costs myself. It's not that bad. I think this year it was around $239.70. Still, Mandrill is Open Source and free, so it's a pain to be paying for the license out of pocket. That's why I setup that Patreon page. It helps cover these ongoing costs. 

I also support archi-lab.net, Bumblebee, MantisShrimp, Mandrill for Grasshopper, MantisShrimp for Grasshopper and a number of other Open Source projects. 

Anyways, I appreciate the support. Thank you!
